# Ramadan Abdunabi
## Week 12 04/08/2025 - 04/10/2025
## Python NumPy Universal Functions

- Universal functions (ufuncs) are functions that operate on NumPy arrays (ndarrays) in an element-by-element

- It is supporting array broadcasting, type casting, and other standard features, offering efficient and flexible computations.

In [1]:
import numpy as np
arr = np.arange(21)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [2]:
# sqrt
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894,
       4.47213595])

In [3]:
#exp()
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04,
       1.62754791e+05, 4.42413392e+05, 1.20260428e+06, 3.26901737e+06,
       8.88611052e+06, 2.41549528e+07, 6.56599691e+07, 1.78482301e+08,
       4.85165195e+08])

In [5]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [7]:
#randn - Generates standard normal distribution sample.
arr1 = np.random.randn(10) 
arr1

array([-1.42898917, -1.18690154,  0.71798883, -1.45044989, -0.16405126,
        1.41788694, -1.18962988,  0.93229736, -0.78655379,  1.0363208 ])

In [8]:
arr2 = np.random.randn(10) 
arr2

array([ 0.07426374,  0.1196052 , -0.11887747, -0.42622435, -0.20237317,
       -0.07726345,  0.56892005, -0.4304097 , -0.37521169, -0.04347447])

In [9]:
# maximum
np.maximum(arr1,arr2)

array([ 0.07426374,  0.1196052 ,  0.71798883, -0.42622435, -0.16405126,
        1.41788694,  0.56892005,  0.93229736, -0.37521169,  1.0363208 ])

In [10]:
np.add(arr1,arr2)

array([-1.35472543, -1.06729634,  0.59911136, -1.87667424, -0.36642442,
        1.3406235 , -0.62070983,  0.50188766, -1.16176548,  0.99284633])

In [11]:
arr1 = np.random.randn(9).reshape(3,3) 
arr1

array([[ 1.28411305,  0.29906694, -0.85039102],
       [-1.27630128, -0.1595289 ,  0.10670824],
       [-1.66711516,  1.02492427, -0.24057362]])

In [12]:
arr2 = np.random.randn(9).reshape(3,3) 
arr2

array([[-1.26605718, -0.62415698, -1.23034723],
       [ 2.25141266,  1.03949299,  0.74039452],
       [ 0.12664783, -1.53592287, -1.57405969]])

In [13]:
np.maximum(arr1,arr2)

array([[ 1.28411305,  0.29906694, -0.85039102],
       [ 2.25141266,  1.03949299,  0.74039452],
       [ 0.12664783,  1.02492427, -0.24057362]])

In [14]:
np.add(arr1,arr2)

array([[ 0.01805588, -0.32509004, -2.08073824],
       [ 0.97511138,  0.87996409,  0.84710276],
       [-1.54046733, -0.5109986 , -1.81463331]])

In [15]:
# Array filtering
arr = np.arange(12).reshape((4,3))
arr

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [16]:
arr > 4

array([[False, False, False],
       [False, False,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [17]:
arr[arr > 4]

array([ 5,  6,  7,  8,  9, 10, 11])

In [19]:
# using where
np.where([False, False, True, False], 1,0)

array([0, 0, 1, 0])

In [20]:
np.where([False, False, True, False], 'Yes','No')

array(['No', 'No', 'Yes', 'No'], dtype='<U3')

In [21]:
np.where(arr > 4, 1,0)

array([[0, 0, 0],
       [0, 0, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [22]:
np.where(arr > 4, arr, 0)

array([[ 0,  0,  0],
       [ 0,  0,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [24]:
np.where((arr < 4) & (arr > 1), arr, 0)

array([[0, 0, 2],
       [3, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [25]:
arr

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [26]:
# Array for random sampling
sample = [True, False]
bool_arr = np.random.choice(sample, size=10)
bool_arr

array([False, False,  True, False,  True, False,  True,  True, False,
        True])

In [28]:
arr1 = np.arange(1,11)
arr2 = arr1 * 10

In [29]:
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [30]:
arr2

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [31]:
np.where(bool_arr, arr1,arr2)

array([10, 20,  3, 40,  5, 60,  7,  8, 90, 10])

In [32]:
np.where(bool_arr, arr1, 'arr2')

array(['arr2', 'arr2', '3', 'arr2', '5', 'arr2', '7', '8', 'arr2', '10'],
      dtype='<U11')

In [33]:
# using list comprehension
list(zip(arr1,arr2,bool_arr))

[(1, 10, False),
 (2, 20, False),
 (3, 30, True),
 (4, 40, False),
 (5, 50, True),
 (6, 60, False),
 (7, 70, True),
 (8, 80, True),
 (9, 90, False),
 (10, 100, True)]

In [34]:
lst = [r1 if c else r2 for (r1,r2,c) in zip(arr1,arr2,bool_arr)]
lst

[10, 20, 3, 40, 5, 60, 7, 8, 90, 10]

In [44]:
# using where with 2-D array
arr1 = np.array([[1,2], [3,4]])
arr2 = np.array([[5,6],[7,8]])
cond = np.array([np.random.choice(sample,size=2), np.random.choice(sample,size=2)])

In [45]:
arr1

array([[1, 2],
       [3, 4]])

In [46]:
arr2

array([[5, 6],
       [7, 8]])

In [47]:
cond

array([[False,  True],
       [ True,  True]])

In [43]:
np.where(cond,arr1,arr2)

array([[1, 6],
       [3, 8]])

In [48]:
# any 
cond.any()

True

In [49]:
arr1

array([[1, 2],
       [3, 4]])

In [51]:
result = arr1 > 3
result

array([[False, False],
       [False,  True]])

In [52]:
result.any()

True

In [53]:
# all()
result.all()

False

In [55]:
# unique()
np.unique(result)

array([False,  True])

In [56]:
fruits = np.array(['Apple','Cherry','Apple', 'Orange', 'Cherry','Banana'])
fruits

array(['Apple', 'Cherry', 'Apple', 'Orange', 'Cherry', 'Banana'],
      dtype='<U6')

In [57]:
np.unique(fruits)

array(['Apple', 'Banana', 'Cherry', 'Orange'], dtype='<U6')

In [58]:
set(fruits)

{'Apple', 'Banana', 'Cherry', 'Orange'}

In [59]:
# in1d
np.in1d(['Apple', 'Cherry', 'Grape'], fruits)

array([ True,  True, False])

In [60]:
'Cherry' in fruits

True

In [2]:
# Descriptive Statistical Measures
import numpy as np
from numpy.random import random, randn, randint

In [3]:
arr = np.arange(1,10).reshape((3,3))
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
np.sum(arr)

45

In [5]:
arr.sum()

45

In [6]:
#axis0
arr.sum(0)

array([12, 15, 18])

In [7]:
#axis1
arr.sum(1)

array([ 6, 15, 24])

In [8]:
np.sum(arr, axis=0)

array([12, 15, 18])

In [9]:
np.sum(arr,axis=1)

array([ 6, 15, 24])

In [10]:
np.sum(arr, axis=None)

45

In [11]:
#mean
arr.mean()

5.0

In [12]:
#axis0
arr.mean(0)

array([4., 5., 6.])

In [13]:
#axis1
arr.mean(1)

array([2., 5., 8.])

In [14]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [16]:
np.mean(arr,axis=None)

5.0

In [17]:
np.mean(arr,axis=0)

array([4., 5., 6.])

In [18]:
np.mean(arr,axis=1)

array([2., 5., 8.])

In [19]:
arr.var()

6.666666666666667

In [20]:
arr.var(axis=0)

array([6., 6., 6.])

In [21]:
arr.var(axis=1)

array([0.66666667, 0.66666667, 0.66666667])

In [22]:
arr.std()

2.581988897471611

In [23]:
arr.std(axis=0)

array([2.44948974, 2.44948974, 2.44948974])

In [25]:
arr.std(axis=1)

array([0.81649658, 0.81649658, 0.81649658])

In [26]:
arr = np.array([3,5,2,7,7,8,1,6,3,9])
arr

array([3, 5, 2, 7, 7, 8, 1, 6, 3, 9])

In [27]:
arr.sort()

In [28]:
arr

array([1, 2, 3, 3, 5, 6, 7, 7, 8, 9])

In [29]:
# dot product of two arrays
arr1 = np.arange(5,20).reshape((3,5))
arr1

array([[ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [30]:
arr2 = (random((5,4)) * 20).astype(int) 
# Return random floats in the half-open interval [0.0, 1.0).
arr2

array([[ 8,  9, 14, 18],
       [ 1, 12,  8, 13],
       [ 9,  8, 15,  4],
       [ 8,  9,  0, 12],
       [ 1,  1,  7, 14]])

In [31]:
arr1.shape

(3, 5)

In [33]:
arr2.shape

(5, 4)

In [34]:
np.dot(arr1,arr2)

array([[ 182,  254,  286,  418],
       [ 317,  449,  506,  723],
       [ 452,  644,  726, 1028]])

In [35]:
random((4,5))

array([[0.37872972, 0.44282806, 0.39959537, 0.1970082 , 0.96833082],
       [0.3530394 , 0.36407049, 0.89947379, 0.72487275, 0.78359325],
       [0.89004659, 0.01364894, 0.5108823 , 0.68276524, 0.84856366],
       [0.28409259, 0.60168958, 0.90801427, 0.03825368, 0.40843291]])

In [45]:
arr = randn(5,5)
arr

array([[ 1.55436185, -0.94717562,  0.08662078, -1.53107994,  0.40834252],
       [ 0.55259992,  2.24882673,  0.84359061, -1.21049581,  0.92230622],
       [-0.65903925,  0.28173403, -0.45162875,  0.31261773,  0.95797114],
       [ 0.46877487,  0.56877399, -0.75198774, -0.99146576, -0.53244782],
       [-1.45541271, -1.42570742,  1.73599381, -0.71057266,  0.46728238]])

In [46]:
arr.mean()

0.02971132414965215

In [50]:
randint(20,50,size=15)

array([31, 32, 41, 49, 36, 20, 35, 35, 35, 31, 23, 35, 38, 40, 29])

In [51]:
# Joining NumPy Arrays
arr1 = np.arange(1,4)
arr2 = np.arange(4,7)

In [52]:
arr1

array([1, 2, 3])

In [53]:
arr2

array([4, 5, 6])

In [55]:
arr = np.concatenate((arr1,arr2))
arr

array([1, 2, 3, 4, 5, 6])

In [57]:
arr1.shape

(3,)

In [58]:
arr2.shape

(3,)

In [59]:
arr.shape

(6,)

In [60]:
arr1 = np.arange(1,5).reshape(2,2)
arr2 = np.arange(5,9).reshape(2,2)

In [61]:
arr1

array([[1, 2],
       [3, 4]])

In [62]:
arr2

array([[5, 6],
       [7, 8]])

In [65]:
arr = np.concatenate((arr1,arr2))
arr

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [64]:
arr.shape

(4, 2)

In [66]:
arr = np.concatenate((arr1,arr2), axis=0)
arr

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [67]:
arr = np.concatenate((arr1,arr2), axis=1)
arr

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [69]:
# Splitting NumPy Arrays
arr = np.arange(1,7)
arr

array([1, 2, 3, 4, 5, 6])

In [70]:
arr_split = np.split(arr,3)
arr_split

[array([1, 2]), array([3, 4]), array([5, 6])]

In [71]:
type(arr_split)

list

In [72]:
arr_split[0]

array([1, 2])

In [73]:
arr_split = np.split(arr,2)
arr_split

[array([1, 2, 3]), array([4, 5, 6])]

In [76]:
arr_split = np.split(arr,4)
arr_split

ValueError: array split does not result in an equal division

In [82]:
# Simple Examples
# Analysis: Calculate the average monthly sales and the percentage change in 
# sales from the beginning to the end of the year.

sales_data = np.array([120, 135, 118, 142, 150, 130, 160, 170, 155, 180, 190, 205])
average_sales = np.mean(sales_data)
percentage_change = ((sales_data[-1] - sales_data[0]) / sales_data[0]) * 100 

print(f'average_sales= {round(average_sales,2)}, percentage_change= {round(percentage_change,2)}')

average_sales= 154.58, percentage_change= 70.83


In [90]:
'''
Data Sample (Customer Age and Spending Score):

Analysis: Calculate the average age and average spending score 
of all customers.

'''
customer_data = np.array([  [25, 60], [35, 80], [22, 40], [45, 90], [30, 70], [50, 30] ])
customer_data

#average = customer_data.mean(axis=0)
#average_age = average[0]
#average_spending_score = average[1]

average_age = customer_data[:,0].mean()
average_spending_score = customer_data[:,1].mean()

print(average_age.astype(int), round(average_spending_score,2))



34 61.67


In [96]:
'''
Healthcare Analysis

Data Sample (Patient ID, Heart Rate, Blood Pressure):

Analysis: For patient ID 1, calculate the average heart rate.
'''

vital_signs = np.array([ [1, 72, 120/80], [2, 85, 130/85], [1, 78, 125/82], [3, 68, 115/75]])
patient1_data = vital_signs[vital_signs[:,0] == 1]



array([[ 1.        , 72.        ,  1.5       ],
       [ 1.        , 78.        ,  1.52439024]])