# Ramadan Abdunabi
## Week11 04/03/2025 - 04/08/2025
### Python numpy creating, processing, transporting arrays


In [1]:
import numpy as np

In [2]:
arr = np.array([[1,2,3,4], [5,6,7,8]])
arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [3]:
arr.ndim

2

In [4]:
arr.shape

(2, 4)

In [5]:
arr.shape[0]

2

In [6]:
arr.shape[1]

4

In [7]:
arr = np.zeros(20) # Return a new array of given shape and type, filled with zeros.
arr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0.])

In [8]:
arr = np.zeros((2,4))
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [9]:
arr = np.zeros((2,5,4))
arr

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [10]:
arr.shape

(2, 5, 4)

In [11]:
arr = np.ones((2,5,4)) # Return a new array of given shape and type, filled with ones.
arr

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [12]:
arr.dtype

dtype('float64')

In [15]:
arr = np.empty((5,2,5)) # creates a new NumPy array with random values.
arr

array([[[             nan,  4.94065646e-324,  6.30427764e-321,
          4.94065646e-324,  4.99994434e-321],
        [ 2.03060980e-321,  4.72326757e-321,  2.03060980e-321,
          5.03946959e-321,  2.03060980e-321]],

       [[ 5.07899484e-321, -1.84698514e-310,  5.29638372e-321,
          2.03060980e-321,  6.44261602e-321],
        [ 2.03060980e-321,  6.30427764e-321,  2.03060980e-321,
          6.50190390e-321, -1.90130823e-310]],

       [[ 6.36356552e-321,  2.03060980e-321,  6.52166653e-321,
          2.03060980e-321,  6.54142915e-321],
        [ 2.03060980e-321,  0.00000000e+000, -1.95579521e-310,
          0.00000000e+000,  0.00000000e+000]],

       [[ 0.00000000e+000,  0.00000000e+000,  0.00000000e+000,
          0.00000000e+000,  0.00000000e+000],
        [-2.01011831e-310,  0.00000000e+000,  0.00000000e+000,
          0.00000000e+000,  0.00000000e+000]],

       [[ 0.00000000e+000,  0.00000000e+000,  0.00000000e+000,
         -2.06444142e-310,  0.00000000e+000],
        [ 0

In [16]:
arr.dtype

dtype('float64')

In [19]:
arr = np.empty((2,5))
arr

array([[3.56043053e-307, 1.60219306e-306, 2.44763557e-307,
        1.69119330e-306, 1.78020984e-306],
       [6.23060065e-307, 1.11260348e-306, 1.37962049e-306,
        2.22521238e-306, 1.24611470e-306]])

In [20]:
arr = np.arange(10,51,5)
arr

array([10, 15, 20, 25, 30, 35, 40, 45, 50])

In [21]:
arr = np.arange(15)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [23]:
# reshape 1-D to 2-D, 3-D, 4-D, etc
# reshape()
arr = np.arange(1,13)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [24]:
arr1 = arr.reshape(2,6)
arr1

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [25]:
arr2 = arr.reshape(2,3,2)
arr2

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

In [26]:
arr.shape

(12,)

In [27]:
arr1.shape

(2, 6)

In [28]:
arr2.shape

(2, 3, 2)

In [30]:
arr[0:3] = [10,11,12]
arr

array([10, 11, 12,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [31]:
arr1

array([[10, 11, 12,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [32]:
arr2

array([[[10, 11],
        [12,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

In [33]:
arr.base

In [34]:
arr1.base

array([10, 11, 12,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [35]:
arr2.base

array([10, 11, 12,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [36]:
# use -1 for Unknown dimensions
arr = np.arange(1,9)
arr

array([1, 2, 3, 4, 5, 6, 7, 8])

In [37]:
arr.reshape(2,2,-1)

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [38]:
arr.reshape(2,-1)

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [39]:
#Iterating 1-D
arr

array([1, 2, 3, 4, 5, 6, 7, 8])

In [40]:
for n in arr:
    print(n * 2)

2
4
6
8
10
12
14
16


In [43]:
for n in arr.reshape((2,4)):
    print(n)

[1 2 3 4]
[5 6 7 8]


In [44]:
for n in arr.reshape((2,4)):
    for m in n:
        print(m)

1
2
3
4
5
6
7
8


In [45]:
for n in np.arange(1,13).reshape((2,3,2)):
    print(n)

[[1 2]
 [3 4]
 [5 6]]
[[ 7  8]
 [ 9 10]
 [11 12]]


In [46]:
for n in np.arange(1,13).reshape((2,3,2)):
    for m in n:
        print(m)

[1 2]
[3 4]
[5 6]
[7 8]
[ 9 10]
[11 12]


In [47]:
for n in np.arange(1,13).reshape((2,3,2)):
    for m in n:
        for v in m:
            print(v)

1
2
3
4
5
6
7
8
9
10
11
12


In [48]:
#nditer iterates on each scalar element in the np array
arr = np.arange(1,13).reshape((2,3,2))
arr

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

In [49]:
for n in np.nditer(arr):
    print(n)

1
2
3
4
5
6
7
8
9
10
11
12


In [53]:
#Multidimensional index iterator.
# Enumerated Iteration Using ndenumerate()
for i,n in np.ndenumerate(np.arange(1,13) * 10):
        print(i,n)

(0,) 10
(1,) 20
(2,) 30
(3,) 40
(4,) 50
(5,) 60
(6,) 70
(7,) 80
(8,) 90
(9,) 100
(10,) 110
(11,) 120


In [55]:
for i,n in np.ndenumerate(np.arange(1,13).reshape((2,6)) * 10):
        print(i,n)

(0, 0) 10
(0, 1) 20
(0, 2) 30
(0, 3) 40
(0, 4) 50
(0, 5) 60
(1, 0) 70
(1, 1) 80
(1, 2) 90
(1, 3) 100
(1, 4) 110
(1, 5) 120


In [56]:
for i,n in np.ndenumerate(np.arange(1,13).reshape((2,2,3)) * 10):
        print(i,n)

(0, 0, 0) 10
(0, 0, 1) 20
(0, 0, 2) 30
(0, 1, 0) 40
(0, 1, 1) 50
(0, 1, 2) 60
(1, 0, 0) 70
(1, 0, 1) 80
(1, 0, 2) 90
(1, 1, 0) 100
(1, 1, 1) 110
(1, 1, 2) 120


In [57]:
np.arange(1,13).reshape((2,2,3)) * 10

array([[[ 10,  20,  30],
        [ 40,  50,  60]],

       [[ 70,  80,  90],
        [100, 110, 120]]])

In [59]:
# operations *, +, -, *, /
arr = np.arange(1,9).reshape((4,2))
arr

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [60]:
arr ** 2

array([[ 1,  4],
       [ 9, 16],
       [25, 36],
       [49, 64]], dtype=int32)

In [61]:
arr * arr

array([[ 1,  4],
       [ 9, 16],
       [25, 36],
       [49, 64]])

In [62]:
arr - arr

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0]])

In [63]:
arr + arr

array([[ 2,  4],
       [ 6,  8],
       [10, 12],
       [14, 16]])

In [64]:
1 / arr

array([[1.        , 0.5       ],
       [0.33333333, 0.25      ],
       [0.2       , 0.16666667],
       [0.14285714, 0.125     ]])

In [65]:
lst = [1,2,3,4,5]
lst

[1, 2, 3, 4, 5]

In [66]:
lst * 2

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [67]:
1 / lst

TypeError: unsupported operand type(s) for /: 'int' and 'list'

In [69]:
# .T Same as self.transpose()
# Reverse or permute the axes of an array; returns the modified array.
arr = np.arange(1,46).reshape((9,5))
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45]])

In [70]:
arr.shape

(9, 5)

In [71]:
arr.T

array([[ 1,  6, 11, 16, 21, 26, 31, 36, 41],
       [ 2,  7, 12, 17, 22, 27, 32, 37, 42],
       [ 3,  8, 13, 18, 23, 28, 33, 38, 43],
       [ 4,  9, 14, 19, 24, 29, 34, 39, 44],
       [ 5, 10, 15, 20, 25, 30, 35, 40, 45]])

In [72]:
arr.shape

(9, 5)

In [73]:
arr.T.shape

(5, 9)

In [74]:
arr_T = arr.T
arr_T

array([[ 1,  6, 11, 16, 21, 26, 31, 36, 41],
       [ 2,  7, 12, 17, 22, 27, 32, 37, 42],
       [ 3,  8, 13, 18, 23, 28, 33, 38, 43],
       [ 4,  9, 14, 19, 24, 29, 34, 39, 44],
       [ 5, 10, 15, 20, 25, 30, 35, 40, 45]])

In [75]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45]])

In [76]:
arr[:5] = 0
arr

array([[ 0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45]])

In [77]:
arr_T

array([[ 0,  0,  0,  0,  0, 26, 31, 36, 41],
       [ 0,  0,  0,  0,  0, 27, 32, 37, 42],
       [ 0,  0,  0,  0,  0, 28, 33, 38, 43],
       [ 0,  0,  0,  0,  0, 29, 34, 39, 44],
       [ 0,  0,  0,  0,  0, 30, 35, 40, 45]])

In [78]:
arr_T.base

array([ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45])

In [79]:
# transpose
arr = np.arange(1,7).reshape((2,3))
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [80]:
arr_t = arr.transpose()
arr_t

array([[1, 4],
       [2, 5],
       [3, 6]])

In [81]:
arr[0] = 10
arr

array([[10, 10, 10],
       [ 4,  5,  6]])

In [82]:
arr_t

array([[10,  4],
       [10,  5],
       [10,  6]])

In [83]:
arr_t.shape

(3, 2)

In [84]:
arr.transpose(0,1)

array([[10, 10, 10],
       [ 4,  5,  6]])

In [85]:
arr.transpose(1,0)

array([[10,  4],
       [10,  5],
       [10,  6]])

In [86]:
arr = np.arange(1,21).reshape(2,5,2)
arr

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8],
        [ 9, 10]],

       [[11, 12],
        [13, 14],
        [15, 16],
        [17, 18],
        [19, 20]]])

In [87]:
arr.shape

(2, 5, 2)

In [88]:
arr_T = arr.T
arr_T

array([[[ 1, 11],
        [ 3, 13],
        [ 5, 15],
        [ 7, 17],
        [ 9, 19]],

       [[ 2, 12],
        [ 4, 14],
        [ 6, 16],
        [ 8, 18],
        [10, 20]]])

In [89]:
arr_T.shape

(2, 5, 2)

In [90]:
arr_t = arr.transpose()
arr_t

array([[[ 1, 11],
        [ 3, 13],
        [ 5, 15],
        [ 7, 17],
        [ 9, 19]],

       [[ 2, 12],
        [ 4, 14],
        [ 6, 16],
        [ 8, 18],
        [10, 20]]])

In [91]:
arr_t = arr.transpose(0,1,2)
arr_t

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8],
        [ 9, 10]],

       [[11, 12],
        [13, 14],
        [15, 16],
        [17, 18],
        [19, 20]]])

In [92]:
arr_t = arr.transpose(1,0,2)
arr_t

array([[[ 1,  2],
        [11, 12]],

       [[ 3,  4],
        [13, 14]],

       [[ 5,  6],
        [15, 16]],

       [[ 7,  8],
        [17, 18]],

       [[ 9, 10],
        [19, 20]]])

In [93]:
arr_t.shape

(5, 2, 2)

In [94]:
arr_t = arr.transpose(2,1,0)
arr_t

array([[[ 1, 11],
        [ 3, 13],
        [ 5, 15],
        [ 7, 17],
        [ 9, 19]],

       [[ 2, 12],
        [ 4, 14],
        [ 6, 16],
        [ 8, 18],
        [10, 20]]])

In [95]:
arr_t = arr.transpose(2,0,1)
arr_t

array([[[ 1,  3,  5,  7,  9],
        [11, 13, 15, 17, 19]],

       [[ 2,  4,  6,  8, 10],
        [12, 14, 16, 18, 20]]])

In [96]:
arr_t.shape

(2, 2, 5)

In [97]:
arr_t.base

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [1]:
# swapaxes
import numpy as np

arr = np.array([[1,2,3,4]])
arr

array([[1, 2, 3, 4]])

In [2]:
arr.ndim

2

In [3]:
arr.shape

(1, 4)

In [4]:
arr.swapaxes(0,1)

array([[1],
       [2],
       [3],
       [4]])

In [5]:
arr.swapaxes(0,1).shape

(4, 1)

In [6]:
arr = np.arange(1,31).reshape(3,5,2)
arr

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8],
        [ 9, 10]],

       [[11, 12],
        [13, 14],
        [15, 16],
        [17, 18],
        [19, 20]],

       [[21, 22],
        [23, 24],
        [25, 26],
        [27, 28],
        [29, 30]]])

In [7]:
arr.ndim

3

In [8]:
arr.shape

(3, 5, 2)

In [9]:
arr.swapaxes(0,2)

array([[[ 1, 11, 21],
        [ 3, 13, 23],
        [ 5, 15, 25],
        [ 7, 17, 27],
        [ 9, 19, 29]],

       [[ 2, 12, 22],
        [ 4, 14, 24],
        [ 6, 16, 26],
        [ 8, 18, 28],
        [10, 20, 30]]])

In [10]:
arr.swapaxes(0,2).shape

(2, 5, 3)

In [12]:
arr.swapaxes(1,2)

array([[[ 1,  3,  5,  7,  9],
        [ 2,  4,  6,  8, 10]],

       [[11, 13, 15, 17, 19],
        [12, 14, 16, 18, 20]],

       [[21, 23, 25, 27, 29],
        [22, 24, 26, 28, 30]]])

In [13]:
arr.swapaxes(1,2).shape

(3, 2, 5)

In [14]:
arr

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8],
        [ 9, 10]],

       [[11, 12],
        [13, 14],
        [15, 16],
        [17, 18],
        [19, 20]],

       [[21, 22],
        [23, 24],
        [25, 26],
        [27, 28],
        [29, 30]]])

In [15]:
arr[0] = 0

In [16]:
arr

array([[[ 0,  0],
        [ 0,  0],
        [ 0,  0],
        [ 0,  0],
        [ 0,  0]],

       [[11, 12],
        [13, 14],
        [15, 16],
        [17, 18],
        [19, 20]],

       [[21, 22],
        [23, 24],
        [25, 26],
        [27, 28],
        [29, 30]]])

In [17]:
arr_s = arr.swapaxes(1,2)
arr_s

array([[[ 0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0]],

       [[11, 13, 15, 17, 19],
        [12, 14, 16, 18, 20]],

       [[21, 23, 25, 27, 29],
        [22, 24, 26, 28, 30]]])

In [18]:
arr[1] = 11
arr

array([[[ 0,  0],
        [ 0,  0],
        [ 0,  0],
        [ 0,  0],
        [ 0,  0]],

       [[11, 11],
        [11, 11],
        [11, 11],
        [11, 11],
        [11, 11]],

       [[21, 22],
        [23, 24],
        [25, 26],
        [27, 28],
        [29, 30]]])

In [19]:
arr_s

array([[[ 0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0]],

       [[11, 11, 11, 11, 11],
        [11, 11, 11, 11, 11]],

       [[21, 23, 25, 27, 29],
        [22, 24, 26, 28, 30]]])

In [20]:
arr.base

array([ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 11, 11, 11, 11, 11, 11, 11,
       11, 11, 11, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [23]:
arr = np.array([[1,2],[3,4],[5,6,7]])
arr

array([list([1, 2]), list([3, 4]), list([5, 6, 7])], dtype=object)

In [24]:
arr.shape

(3,)

In [25]:
arr[0]

[1, 2]