# Ramadan Abdunabi
## Week11 04/01/2025
### Python Numpy - Processing Arrays With Data Types

# Primitive Data Types in Python
- String
- Integer
- float
- boolean


# Data Types in NumPy

- i - integer
- b - boolean
- u - unsigned integer
- f - float
- c - complex float
- m - timedelta
- M - datetime
- O - object
- S - string
- U - unicode string
- V - fixed chunk of memory for other type ( void )


In [1]:
import numpy as np

In [2]:
arr = np.array(list(range(5,16,5)))
arr

array([ 5, 10, 15])

In [3]:
arr.dtype

dtype('int32')

In [8]:
lst1 = [1,2,3,4,5]
lst2 = [11,12,13,14,15]

In [9]:
lst1

[1, 2, 3, 4, 5]

In [10]:
lst2

[11, 12, 13, 14, 15]

In [11]:
arr = np.array([lst1,lst2])
arr

array([[ 1,  2,  3,  4,  5],
       [11, 12, 13, 14, 15]])

In [12]:
arr.dtype

dtype('int32')

In [13]:
arr_str = np.array(['Orange', 'Apple', 'Cherry','Grape'])
arr_str

array(['Orange', 'Apple', 'Cherry', 'Grape'], dtype='<U6')

In [14]:
arr_str.dtype

dtype('<U6')

In [15]:
lst = ['Orange', 'Apple', 'Cherry','Grape', True, False, 1,2,3,4,5, 10.5,11.5,(1,2,3,4), {1,2,3,4},[1,2,3,4]]
lst

['Orange',
 'Apple',
 'Cherry',
 'Grape',
 True,
 False,
 1,
 2,
 3,
 4,
 5,
 10.5,
 11.5,
 (1, 2, 3, 4),
 {1, 2, 3, 4},
 [1, 2, 3, 4]]

In [16]:
arr_obj = np.array(lst)
arr_obj

array(['Orange', 'Apple', 'Cherry', 'Grape', True, False, 1, 2, 3, 4, 5,
       10.5, 11.5, (1, 2, 3, 4), {1, 2, 3, 4}, list([1, 2, 3, 4])],
      dtype=object)

In [17]:
type(lst)

list

In [18]:
type(arr_obj)

numpy.ndarray

In [19]:
# create numpy array with data type
arr = np.array([10,11,12,13,14,15],dtype='S')
arr

array([b'10', b'11', b'12', b'13', b'14', b'15'], dtype='|S2')

In [20]:
arr.dtype

dtype('S2')

In [21]:
arr = np.array([10,11,12,13,14,15],dtype='i4')
arr

array([10, 11, 12, 13, 14, 15])

In [22]:
arr.dtype

dtype('int32')

In [23]:
arr = np.array([10,11,12,13,14,15],dtype='i8')
arr

array([10, 11, 12, 13, 14, 15], dtype=int64)

In [24]:
arr.dtype

dtype('int64')

In [25]:
# Converting Data Type on Existing Numpy Arrays
arr = np.array(['1','2','4','5'], dtype='i4')
arr

array([1, 2, 4, 5])

In [26]:
arr = np.array([78.5,88.9,90.3,89.9])
arr

array([78.5, 88.9, 90.3, 89.9])

In [27]:
arr.dtype

dtype('float64')

In [28]:
arr.astype('i')

array([78, 88, 90, 89], dtype=int32)

In [29]:
arr

array([78.5, 88.9, 90.3, 89.9])

In [30]:
arr = arr.astype('i8')
arr

array([78, 88, 90, 89], dtype=int64)

In [31]:
arr = np.array([1,2,3,4,5,6,0,0,0,1,2,0,0])
arr

array([1, 2, 3, 4, 5, 6, 0, 0, 0, 1, 2, 0, 0])

In [32]:
arr.astype(bool)

array([ True,  True,  True,  True,  True,  True, False, False, False,
        True,  True, False, False])

In [33]:
# NumPy Array Copy vs View
arr = np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [34]:
arr2 = arr

In [35]:
arr2

array([1, 2, 3, 4, 5])

In [36]:
arr[0] = 9999
arr

array([9999,    2,    3,    4,    5])

In [37]:
arr2

array([9999,    2,    3,    4,    5])

In [38]:
arr

array([9999,    2,    3,    4,    5])

In [39]:
arr3 = arr.view()
arr3

array([9999,    2,    3,    4,    5])

In [40]:
arr[-1] = 5555
arr

array([9999,    2,    3,    4, 5555])

In [41]:
arr3

array([9999,    2,    3,    4, 5555])

In [42]:
arr2

array([9999,    2,    3,    4, 5555])

In [43]:
arr = np.array([1,2,3,4,5,6])
arr

array([1, 2, 3, 4, 5, 6])

In [44]:
arr2

array([9999,    2,    3,    4, 5555])

In [45]:
arr3

array([9999,    2,    3,    4, 5555])

In [46]:
arr

array([1, 2, 3, 4, 5, 6])

In [47]:
arr_c = arr.copy()
arr_c

array([1, 2, 3, 4, 5, 6])

In [48]:
arr

array([1, 2, 3, 4, 5, 6])

In [49]:
arr[0] = 11
arr

array([11,  2,  3,  4,  5,  6])

In [50]:
arr_c

array([1, 2, 3, 4, 5, 6])

In [51]:
arr.base

In [52]:
arr_c.base

In [53]:
arr2.base

In [54]:
arr3.base

array([9999,    2,    3,    4, 5555])