# Name Ramadan Abdunabi
## Week 10 - 03/25/2025 - 04/01/2025
### Python numpy Into

- NumPy is a Python library.
- NumPy is used for working with arrays.
- NumPy is short for "Numerical Python".
- Arrays are very frequently used in data science, where speed and resources are very important
- NumPy aims to provide an array object that is up to 50x faster than traditional Python lists.
- The array object in NumPy is called ndarray
-  NumPy arrays are stored at one continuous place in memory unlike lists
- This behavior is called locality of reference in computer scienc- NumPy is a - Python library and is written partially in Python, most of the parts that require fast computation are written in C or C++

In [1]:
import numpy as np

In [2]:
np.__version__

'1.18.5'

In [3]:
# Create a NumPy ndarray Object

arr = np.array([1,2,3,4,5,6,7,8,9,10])
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
type(arr)

numpy.ndarray

In [5]:
arr = np.array((1,2,3,4,5,6,7,8,9,10))
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [6]:
# Dimensions in Arrays.
# A dimension in arrays is one level of array depth (nested arrays).
# nested array: are arrays that have arrays as their elements.

'''
0-D Arrays, or Scalars, are the elements in an array

'''

arr_0D = np.array(20)
arr_0D

array(20)

In [7]:
print(arr_0D)

20


In [8]:
arr_0D.ndim

0

In [9]:
arr_0D.shape

()

In [10]:
'''
1-D Arrays
An array that has 0-D arrays as its elements.
'''
arr_1D = np.array([1,2,3,4,5,6,7,8,9,10])
arr_1D

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [11]:
arr_1D.ndim

1

In [12]:
arr_1D.shape

(10,)

In [13]:
'''
2-D Arrays
An array that has 1-D arrays as its elements
'''

arr_2D = np.array([ [1,2,3,10], [4,5,6,11], [7,8,9,12]  ])
arr_2D

array([[ 1,  2,  3, 10],
       [ 4,  5,  6, 11],
       [ 7,  8,  9, 12]])

In [14]:
print(arr_2D)

[[ 1  2  3 10]
 [ 4  5  6 11]
 [ 7  8  9 12]]


In [15]:
arr_2D.ndim

2

In [16]:
arr_2D.shape

(3, 4)

In [17]:
'''
3-D array
An array that has 2-D arrays (matrices) as its elements
'''

arr_3D = np.array([ [ [1,2,3], [4,5,6]  ], [ [10,11,12], [13,14,15]  ]  ])
arr_3D

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[10, 11, 12],
        [13, 14, 15]]])

In [18]:
arr_3D.ndim

3

In [19]:
arr_3D.shape

(2, 2, 3)

In [20]:
#4D array
arr_4D = np.array([1,2,3,4,5],ndmin=4)
arr_4D

array([[[[1, 2, 3, 4, 5]]]])

In [21]:
arr_4D.ndim

4

In [22]:
arr_4D.shape

(1, 1, 1, 5)

In [23]:
a = np.array([[[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]],[[13,14,15],[16,17,18]]], [[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]],[[13,14,15],[16,17,18]]], [[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]],[[13,14,15],[16,17,18]]], [[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]],[[13,14,15],[16,17,18]]]])
a

array([[[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]],

        [[13, 14, 15],
         [16, 17, 18]]],


       [[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]],

        [[13, 14, 15],
         [16, 17, 18]]],


       [[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]],

        [[13, 14, 15],
         [16, 17, 18]]],


       [[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]],

        [[13, 14, 15],
         [16, 17, 18]]]])

In [24]:
# Array Indexing
arr_1D

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [25]:
arr_1D[0]

1

In [26]:
arr_1D[-1]

10

In [27]:
arr_1D[3]

4

In [28]:
arr_2D

array([[ 1,  2,  3, 10],
       [ 4,  5,  6, 11],
       [ 7,  8,  9, 12]])

In [29]:
arr_2D.shape

(3, 4)

In [30]:
arr_2D[0]

array([ 1,  2,  3, 10])

In [31]:
arr_2D[-1]

array([ 7,  8,  9, 12])

In [32]:
arr_2D[1,1]

5

In [33]:
arr_2D[-1,-1]

12

In [34]:
arr_3D

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[10, 11, 12],
        [13, 14, 15]]])

In [35]:
arr_3D.shape

(2, 2, 3)

In [36]:
arr_3D[1]

array([[10, 11, 12],
       [13, 14, 15]])

In [37]:
arr_3D[1,0]

array([10, 11, 12])

In [38]:
arr_3D[1,0,-1]

12

In [39]:
arr_3D[0,-1,0]

4

In [40]:
arr_3D[1,0]

array([10, 11, 12])

In [41]:
# slicing np arrays
# [start:end:step] start default 0, end index is excluded, and step is considered 1, 
arr_1D

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [42]:
arr_1D[:5]

array([1, 2, 3, 4, 5])

In [43]:
arr_1D[-3:]

array([ 8,  9, 10])

In [44]:
arr_1D[::]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [45]:
arr_1D[::2]

array([1, 3, 5, 7, 9])

In [46]:
arr_1D


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [47]:
# Slicing 2-D Arrays
arr_2D

array([[ 1,  2,  3, 10],
       [ 4,  5,  6, 11],
       [ 7,  8,  9, 12]])

In [48]:
# [rows,column] apply start:stop:step for rows and culumn, axis0 and axis1
arr_2D.shape

(3, 4)

In [49]:
arr_2D[1]

array([ 4,  5,  6, 11])

In [50]:
arr_2D[1,-1]

11

In [51]:
arr_2D[1,-3:]

array([ 5,  6, 11])

In [52]:
arr_2D

array([[ 1,  2,  3, 10],
       [ 4,  5,  6, 11],
       [ 7,  8,  9, 12]])

In [54]:
arr_2D[:2]

array([[ 1,  2,  3, 10],
       [ 4,  5,  6, 11]])

In [55]:
arr_2D[:2,-1]

array([10, 11])

In [56]:
arr_2D[:2,-2:]

array([[ 3, 10],
       [ 6, 11]])

In [57]:
arr_2D

array([[ 1,  2,  3, 10],
       [ 4,  5,  6, 11],
       [ 7,  8,  9, 12]])

In [58]:
arr_2D[::,:2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [59]:
# 3-D arrays
# [axis0, axis1, axis2] slice or index each axis, layer
arr_3D


array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[10, 11, 12],
        [13, 14, 15]]])

In [61]:
arr_3D.shape

(2, 2, 3)

In [62]:
arr_3D[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [63]:
arr_3D.ndim

3

In [64]:
arr_3D[0].ndim

2

In [65]:
arr_3D[0,0]

array([1, 2, 3])

In [66]:
arr_3D[0,0,-1]

3

In [74]:
arr_3D[1,1,-1]

15

In [76]:
arr_3D[1,:2,:2]

array([[10, 11],
       [13, 14]])

In [79]:
arr_3D[0,1,-2:]

array([5, 6])

In [80]:
arr_3D

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[10, 11, 12],
        [13, 14, 15]]])

In [85]:
arr_3D[...,::,:2]

array([[[ 1,  2],
        [ 4,  5]],

       [[10, 11],
        [13, 14]]])

In [88]:
arr_3D[...,::,-2:]

array([[[ 2,  3],
        [ 5,  6]],

       [[11, 12],
        [14, 15]]])

In [89]:
arr_3D[...,::,-2:].ndim

3