# Ramadan Abdunabi
## Week 12 04/04/2024
## Python NumPy Universal Functions

In [1]:
# Universal functions are a powerful tool 
# for performing mathematical operations on NumPy arrays, ndarray.
# This makes them much faster than looping over 
# the elements of an array and performing the operation manually.
import numpy as np

arr = np.arange(21)
arr


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [2]:
# sqrt
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894,
       4.47213595])

In [3]:
#exp()
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04,
       1.62754791e+05, 4.42413392e+05, 1.20260428e+06, 3.26901737e+06,
       8.88611052e+06, 2.41549528e+07, 6.56599691e+07, 1.78482301e+08,
       4.85165195e+08])

In [4]:
#randn - Generates standard normal distribution sample.
arr = np.random.randn(10)
arr

array([ 0.47499082, -0.64776377, -1.4207349 ,  0.60548069, -0.34402698,
       -1.87209015, -0.25632505,  0.39329368, -0.40581853, -1.01915212])

In [5]:
arr = np.random.randn(20)
arr

array([-0.71062225, -0.20558342, -1.26632239, -0.93928894,  0.89088607,
        0.78121472, -1.60970877, -1.84086041,  1.233896  ,  0.05282842,
       -1.06078812,  1.69718777, -0.1841143 , -0.15513808, -1.78166986,
       -0.53210096, -0.41224298, -0.67497482, -0.44977871, -1.85771609])

In [6]:
arr1 = np.random.randn(10)
arr1

array([ 0.5806955 , -1.03927149,  0.49847997,  0.58278546, -0.77370931,
        0.57510632, -1.60581187, -1.1949627 , -2.02456206, -0.6305926 ])

In [7]:
arr2 = np.random.randn(10)
arr2

array([-0.03438652,  1.85637586, -1.47939587, -1.27305876,  0.34371134,
       -0.7498267 , -0.56901916,  0.02818979, -0.72090537, -0.94609886])

In [8]:
np.add(arr1,arr2)

array([ 0.54630897,  0.81710437, -0.9809159 , -0.6902733 , -0.42999797,
       -0.17472038, -2.17483103, -1.16677291, -2.74546743, -1.57669146])

In [9]:
# maximum
np.maximum(arr1,arr2)

array([ 0.5806955 ,  1.85637586,  0.49847997,  0.58278546,  0.34371134,
        0.57510632, -0.56901916,  0.02818979, -0.72090537, -0.6305926 ])

In [10]:
arr1 = np.arange(9).reshape(3,3)
arr1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [11]:
arr2 = np.ones(9).reshape(3,3)
arr2

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [12]:
np.add(arr1,arr2)

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [13]:
# Array filtering
arr = np.arange(9).reshape((3,3))
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [14]:
arr > 4

array([[False, False, False],
       [False, False,  True],
       [ True,  True,  True]])

In [15]:
# where
# replace values of an array, using where
# Return elements chosen from `x` or `y` depending on `condition`.
np.where(arr>4, arr, 0)

array([[0, 0, 0],
       [0, 0, 5],
       [6, 7, 8]])

In [16]:
np.where(arr < 4, arr, 0)

array([[0, 1, 2],
       [3, 0, 0],
       [0, 0, 0]])

In [17]:
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [18]:
from numpy.random import randn
arr = randn(3,3)
arr

array([[ 2.33028593, -0.30580798,  1.46080437],
       [-0.44962983,  0.25968495, -2.96173678],
       [ 1.35615262, -0.14726485,  1.58827503]])

In [19]:
np.where(arr<0,0,arr)

array([[2.33028593, 0.        , 1.46080437],
       [0.        , 0.25968495, 0.        ],
       [1.35615262, 0.        , 1.58827503]])

In [20]:
np.where([True,False,True,False], 1,0)

array([1, 0, 1, 0])

In [24]:
sample_bool_arr = [True,False]
arr_bool = np.random.choice(sample_bool_arr, size=10)
arr_bool

array([False, False, False, False,  True,  True,  True, False, False,
       False])

In [25]:
arr1 = np.arange(1,6)
arr2 = arr1*10
arr_bool = np.random.choice(sample_bool_arr, size=5)



In [26]:
arr1

array([1, 2, 3, 4, 5])

In [27]:
arr2

array([10, 20, 30, 40, 50])

In [29]:
arr_bool

array([ True,  True, False, False,  True])

In [30]:
np.where(arr_bool,arr1,arr2)

array([ 1,  2, 30, 40,  5])

In [31]:
[r1 if c else r2 for r1,r2,c in zip(arr1,arr2,arr_bool)]

[1, 2, 30, 40, 5]

In [32]:
list(zip(arr1,arr2,arr_bool))

[(1, 10, True), (2, 20, True), (3, 30, False), (4, 40, False), (5, 50, True)]

In [37]:
# using where with 2-D array
arr1 = np.arange(1,5).reshape(2,2)
arr2 = np.arange(5,9).reshape(2,2)
arr_bool = np.array([np.random.choice(sample_bool_arr, size=2), 
                               np.random.choice(sample_bool_arr, size=2)])

In [38]:
arr1

array([[1, 2],
       [3, 4]])

In [39]:
arr2

array([[5, 6],
       [7, 8]])

In [40]:
arr_bool

array([[False,  True],
       [ True, False]])

In [41]:
arr_bool = np.random.choice(sample_bool_arr, size=4).reshape(2,2)
arr_bool

array([[False,  True],
       [ True, False]])

In [42]:
np.where(arr_bool,arr1,arr2)

array([[5, 2],
       [3, 8]])

In [44]:
# any - Returns True if any of the elements of `a` evaluate to True.
arr_bool = np.random.choice(sample_bool_arr, size=5)
arr_bool

array([False, False,  True,  True, False])

In [45]:
arr_bool.any()

True

In [46]:
# all
arr_bool.all()

False

In [47]:
# unique()
fruits = np.array(['Apple','Cherry','Apple', 'Orange', 'Cherry','Banana'])
np.unique(fruits)

array(['Apple', 'Banana', 'Cherry', 'Orange'], dtype='<U6')

In [48]:
#in1d
np.in1d(['Apple','Cherry','Grape'],fruits)

array([ True,  True, False])

In [49]:
# Descriptive Statistical Measures
arr = np.arange(1,10).reshape(3,3)
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [50]:
arr.shape

(3, 3)

In [51]:
arr.sum()

45

In [52]:
arr.sum(0) #axis0

array([12, 15, 18])

In [53]:
arr.sum(1) #axis0

array([ 6, 15, 24])

In [54]:
np.sum(arr,axis=0)

array([12, 15, 18])

In [55]:
np.sum(arr,axis=1)

array([ 6, 15, 24])

In [56]:
arr.mean()

5.0

In [57]:
arr.mean(0) #axis0

array([4., 5., 6.])

In [58]:
arr.mean(1) #axis1

array([2., 5., 8.])

In [59]:
np.mean(arr,axis=0)

array([4., 5., 6.])

In [61]:
np.mean(arr,axis=1)

array([2., 5., 8.])

In [62]:
arr.var()

6.666666666666667

In [63]:
arr.std()

2.581988897471611

In [64]:
arr = np.array([2,5,1,8,3,5,8,9,2,3,4,6,7])
arr.sort()

In [65]:
arr

array([1, 2, 2, 3, 3, 4, 5, 5, 6, 7, 8, 8, 9])

In [66]:
# Random - Different random [0.0,1.0)
arr = np.random.random((4,4))
arr


array([[0.17686531, 0.0642685 , 0.48027456, 0.68390937],
       [0.99536682, 0.15490533, 0.89484001, 0.93213252],
       [0.51232065, 0.23657162, 0.66855073, 0.58537529],
       [0.39709031, 0.38370114, 0.72464858, 0.93472432]])

In [67]:
np.random.randint(10,50)

42

In [69]:
# concatenate or join arrays
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.concatenate((arr1,arr2))
arr

array([1, 2, 3, 4, 5, 6])