# Ramadan Abdunabi
## Week11 03/28/2024
### Python Numpy - Processing Arrays

In [1]:
import numpy as np

In [2]:
lst = [11,22,33,44,55,66,77]
lst

[11, 22, 33, 44, 55, 66, 77]

In [3]:
arr = np.array(lst)
arr

array([11, 22, 33, 44, 55, 66, 77])

In [4]:
arr.dtype

dtype('int32')

In [5]:
# creating an array from a nested list
lst1 = [1,2,3,4,5]
lst2 = [11,22,33,44,55]

lst = [lst1,lst2]
lst

[[1, 2, 3, 4, 5], [11, 22, 33, 44, 55]]

In [6]:
arr = np.array(lst)
arr

array([[ 1,  2,  3,  4,  5],
       [11, 22, 33, 44, 55]])

In [7]:
arr.ndim

2

In [8]:
arr.shape

(2, 5)

In [9]:
arr.dtype

dtype('int32')

In [10]:
arr = np.array(['Orange', 'Apple', 'Cherry','Grape'])
arr

array(['Orange', 'Apple', 'Cherry', 'Grape'], dtype='<U6')

In [11]:
arr.dtype

dtype('<U6')

In [12]:
arr = np.array(['Orange', 'Apple', 'Cherry','Grape',1,2,3,4,5, [6,7,8,9,10], 
                                                                (10,11,12)])
arr

array(['Orange', 'Apple', 'Cherry', 'Grape', 1, 2, 3, 4, 5,
       list([6, 7, 8, 9, 10]), (10, 11, 12)], dtype=object)

In [13]:
arr.dtype

dtype('O')

In [14]:
# Convert Data Types
arr = np.array([10,11,12,13,14,15], dtype='S')
arr

array([b'10', b'11', b'12', b'13', b'14', b'15'], dtype='|S2')

In [15]:
arr.dtype

dtype('S2')

In [18]:
arr = np.array([1,2,3,4,5], dtype='i8')
arr

array([1, 2, 3, 4, 5], dtype=int64)

In [19]:
arr.dtype

dtype('int64')

In [20]:
arr = np.array([78.5,88.9,90.3,89.9])
arr

array([78.5, 88.9, 90.3, 89.9])

In [21]:
arr.dtype

dtype('float64')

In [22]:
arr_int = arr.astype('i')
arr_int

array([78, 88, 90, 89], dtype=int32)

In [23]:
arr_int.dtype

dtype('int32')

In [24]:
arr = np.array([1,0,0,1,2,1,0,0,1,2,1,3])
arr

array([1, 0, 0, 1, 2, 1, 0, 0, 1, 2, 1, 3])

In [25]:
arr.dtype

dtype('int32')

In [26]:
arr_bool = arr.astype(bool)
arr_bool

array([ True, False, False,  True,  True,  True, False, False,  True,
        True,  True,  True])

In [27]:
arr_bool.dtype

dtype('bool')

In [28]:
arr

array([1, 0, 0, 1, 2, 1, 0, 0, 1, 2, 1, 3])

In [29]:
# NumPy Array Copy, View, and Assignment (=)
# copy
arr = np.array([1,2,3,4,5,6,7,8])
arr

array([1, 2, 3, 4, 5, 6, 7, 8])

In [30]:
arr_copy = arr.copy()
arr_copy

array([1, 2, 3, 4, 5, 6, 7, 8])

In [31]:
arr[0] = 10
arr

array([10,  2,  3,  4,  5,  6,  7,  8])

In [32]:
arr_copy

array([1, 2, 3, 4, 5, 6, 7, 8])

In [33]:
#view
arr = np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [34]:
arr_view = arr.view()
arr_view

array([1, 2, 3, 4, 5])

In [35]:
arr[-1] = 99
arr

array([ 1,  2,  3,  4, 99])

In [36]:
arr_view

array([ 1,  2,  3,  4, 99])

In [37]:
# assignment =
arr = np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [38]:
arr_assign = arr
arr_assign

array([1, 2, 3, 4, 5])

In [39]:
arr[1] = 200
arr

array([  1, 200,   3,   4,   5])

In [40]:
arr_assign

array([  1, 200,   3,   4,   5])

In [41]:
# using base
print(arr.base)
print(arr_copy.base)
print(arr_view.base)
print(arr_assign.base)

None
None
[ 1  2  3  4 99]
None


In [42]:
#shape gives the number of elements in each dimension
lst1 = [1,2,3,4,5]
lst2 = [11,22,33,44,55]

lst = [lst1,lst2]

arr = np.array(lst)
arr

array([[ 1,  2,  3,  4,  5],
       [11, 22, 33, 44, 55]])

In [43]:
arr.ndim

2

In [44]:
arr.shape

(2, 5)

In [45]:
# Reading data from files
f = open("data.txt", "w") 
f.write("1, 2, 3\n")
f.write("4, 5, 6")
f.close()

In [47]:
r = open("data.txt", "r")
print(r.read())

1, 2, 3
4, 5, 6


In [48]:
# Using np.genfromtxt
arr = np.genfromtxt("data.txt", dtype=None, delimiter=",")
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [49]:
arr.ndim

2

In [50]:
arr.shape

(2, 3)

In [51]:
arr.dtype

dtype('int32')

In [52]:
# Using np.loadtxt
arr = np.loadtxt("data1.txt", dtype='i8')
arr

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]], dtype=int64)

In [53]:
arr.ndim

2

In [54]:
arr.shape

(5, 2)

In [55]:
# zeros
#Return a new array of given shape and type, filled with zeros.
arr = np.zeros(10)
arr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [56]:
arr.dtype

dtype('float64')

In [57]:
arr = np.zeros((5,5))
arr

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [58]:
arr.shape

(5, 5)

In [59]:
arr.ndim

2

In [60]:
arr.dtype

dtype('float64')

In [61]:
arr = np.zeros((5,4,6))
arr

array([[[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]]])

In [62]:
# ones
# #Return a new array of given shape and type, filled with ones.
arr = np.ones((5,5), dtype=int)
arr

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [63]:
arr = np.ones((3,4,4,5), dtype=int)
arr

array([[[[1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1]],

        [[1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1]],

        [[1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1]],

        [[1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1]]],


       [[[1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1]],

        [[1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1]],

        [[1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1]],

        [[1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1]]],


       [[[1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1]],

        [[1, 1, 1, 1, 1],
         [1, 1, 

In [64]:
arr = np.empty((5,5), dtype=int)
arr

array([[1970562386,  539782770, 1970365779, 1701015141, 1849761836],
       [1142959225,  745825129, 1886737440,  539780460, 1954047316],
       [ 539774793, 1919252079, 1684107116, 1884233772, 1852795252],
       [ 170683489,  538976288, 1869180501, 1411394670, 1449488505],
       [ 539783777, 1819042115, 1701601889, 2035556396,  688547184]])

In [66]:
arr = np.empty((5,5))
arr

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [67]:
arr = np.empty((2,3,4))
arr

array([[[6.23042070e-307, 3.22651328e-307, 8.45599366e-307,
         7.56593017e-307],
        [1.95821439e-306, 2.22522597e-306, 8.90094053e-307,
         1.86919378e-306],
        [1.24610383e-306, 1.69118108e-306, 8.06632139e-308,
         1.20160711e-306]],

       [[1.69119330e-306, 8.90098127e-307, 1.06811422e-306,
         6.89806849e-307],
        [1.78021391e-306, 2.22523140e-306, 1.06811354e-306,
         1.69118108e-306],
        [1.11261027e-306, 6.23037996e-307, 8.90104239e-307,
         1.42410974e-306]]])

In [68]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [69]:
arr = np.arange(10,100,5)
arr

array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90,
       95])

In [95]:
arr = np.arange(1,13)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [96]:
# Reshape an array
arr = np.arange(1,13)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [97]:
arr_2d = arr.reshape(3,4)
arr_2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [91]:
arr_3d = arr.reshape(2,2,3)
arr_3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [98]:
# is reshape copy or view
arr[0] = 100
arr

array([100,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12])

In [93]:
arr_2d

array([[100,   2,   3,   4],
       [  5,   6,   7,   8],
       [  9,  10,  11,  12]])

In [94]:
arr_3d

array([[[100,   2,   3],
        [  4,   5,   6]],

       [[  7,   8,   9],
        [ 10,  11,  12]]])

In [74]:
arr_3d.ndim

3

In [75]:
arr_3d = arr.reshape(2,3,2)
arr_3d

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

In [76]:
arr_3d = arr.reshape(2,3,3)
arr_3d

ValueError: cannot reshape array of size 12 into shape (2,3,3)

In [83]:
arr = np.arange(1,16).reshape(5,3)
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

In [84]:
arr.base

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [86]:
arr_3d.base

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [87]:
arr[0] = 100

In [88]:
arr

array([[100, 100, 100],
       [  4,   5,   6],
       [  7,   8,   9],
       [ 10,  11,  12],
       [ 13,  14,  15]])