# Ramadan Abdunabi
## Week10 10/22/2024 - 10/24/2024
### Python Numpy - Processing Arrays

In [1]:
import numpy as np

In [2]:
lst1 = list(range(1,6))
lst2 = list(range(6,11))

In [3]:
lst1

[1, 2, 3, 4, 5]

In [4]:
lst2

[6, 7, 8, 9, 10]

In [5]:
lst = [lst1,lst2]
lst

[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]

In [6]:
arr_2d = np.array(lst)
arr_2d

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [7]:
arr_2d.shape

(2, 5)

In [8]:
arr_2d.dtype

dtype('int32')

In [9]:
arr_1d = np.array(['Orange', 'Apple', 'Cherry','Grape'])
arr_1d

array(['Orange', 'Apple', 'Cherry', 'Grape'], dtype='<U6')

In [10]:
arr_1d.dtype

dtype('<U6')

In [11]:
arr = np.array(['Orange', 'Apple', 'Cherry','Grape', 1.5, 2.8, 4.9, (1,2,3,4),[4,5,6], True, False])
arr

array(['Orange', 'Apple', 'Cherry', 'Grape', 1.5, 2.8, 4.9, (1, 2, 3, 4),
       list([4, 5, 6]), True, False], dtype=object)

In [12]:
arr.dtype

dtype('O')

In [13]:
# Convert Data Types
arr = np.array([10,11,12,13,14,15], dtype='S')
arr

array([b'10', b'11', b'12', b'13', b'14', b'15'], dtype='|S2')

In [14]:
print(arr)

[b'10' b'11' b'12' b'13' b'14' b'15']


In [15]:
arr[0]

b'10'

In [16]:
arr = np.array(list(range(1,6)), dtype='i4')
arr

array([1, 2, 3, 4, 5])

In [17]:
arr.dtype

dtype('int32')

In [18]:
arr = np.array(list(range(5,11)), dtype='i8')
arr

array([ 5,  6,  7,  8,  9, 10], dtype=int64)

In [19]:
arr.dtype

dtype('int64')

In [20]:
# Converting Data Type on Existing Arrays
arr = np.array([78.5,88.9,90.3,89.9,87.6])
arr

array([78.5, 88.9, 90.3, 89.9, 87.6])

In [21]:
arr.dtype

dtype('float64')

In [22]:
# astype()
arr_int = arr.astype('i') 
arr_int

array([78, 88, 90, 89, 87], dtype=int32)

In [23]:
arr

array([78.5, 88.9, 90.3, 89.9, 87.6])

In [24]:
arr_int

array([78, 88, 90, 89, 87], dtype=int32)

In [25]:
arr = np.array([1,0,2,3,1,0,0,2])
arr

array([1, 0, 2, 3, 1, 0, 0, 2])

In [26]:
arr_b = arr.astype(bool)
arr_b

array([ True, False,  True,  True,  True, False, False,  True])

In [28]:
# NumPy Array Copy vs View
'''
The Difference Between Copy and View:
Copy is a new array, and the view is just a view of the original array
'''

arr1 = np.array(list(range(10,16)))
arr1


array([10, 11, 12, 13, 14, 15])

In [29]:
arr2 = arr1
arr2

array([10, 11, 12, 13, 14, 15])

In [30]:
arr1[:3] = [1,2,3]
arr1

array([ 1,  2,  3, 13, 14, 15])

In [31]:
arr2

array([ 1,  2,  3, 13, 14, 15])

In [32]:
arr1

array([ 1,  2,  3, 13, 14, 15])

In [33]:
arr2_copy = arr1.copy() # the copy is a new numpy array
arr2_copy

array([ 1,  2,  3, 13, 14, 15])

In [34]:
arr1[:3] = [11,22,33]
arr1

array([11, 22, 33, 13, 14, 15])

In [35]:
arr2_copy

array([ 1,  2,  3, 13, 14, 15])

In [36]:
arr1

array([11, 22, 33, 13, 14, 15])

In [37]:
arr2_view = arr1.view() #a view of the original array
arr2_view

array([11, 22, 33, 13, 14, 15])

In [38]:
arr1[-3:] = [0,1,2]
arr1

array([11, 22, 33,  0,  1,  2])

In [39]:
arr2_view

array([11, 22, 33,  0,  1,  2])

In [40]:
print(arr2_copy.base)

None


In [41]:
print(arr2_view.base)

[11 22 33  0  1  2]


In [42]:
# shape gives the number of elements in each dimension
arr = np.array([list(range(1,6)), list(range(6,11))])
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [43]:
arr.shape

(2, 5)

In [45]:
arr.shape[0]

2

In [46]:
arr.shape[1]

5

In [47]:
# Stacking: Several arrays can be stacked together along different axes.
# np.vstack: To stack arrays along vertical axis.
# np.hstack: To stack arrays along horizontal axis
a =  np.array([[1, 2],
              [3, 4]])

b = np.array([[5, 6],
              [7, 8]])

In [48]:
a

array([[1, 2],
       [3, 4]])

In [49]:
b

array([[5, 6],
       [7, 8]])

In [50]:
a.ndim

2

In [51]:
len(a)

2

In [52]:
a.shape

(2, 2)

In [53]:
# vertical stacking
np.vstack((a,b))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [54]:
# horizontal stacking
np.hstack((a,b))

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [55]:
np.hstack((b,a))

array([[5, 6, 1, 2],
       [7, 8, 3, 4]])

In [56]:
# create numpy array from files
# write data
f = open("data.txt", "w")
f.write("1, 2, 3\n")
f.write("4, 5, 6")
f.close()

In [58]:
#read
f = open("data.txt", "r")
print(f.read())

1, 2, 3
4, 5, 6


In [59]:
# Using np.genfromtxt
arr = np.genfromtxt("data.txt", dtype=None, delimiter=",")
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [60]:
arr.ndim

2

In [61]:
arr.shape

(2, 3)

In [66]:
# Using np.loadtxt
arr = np.loadtxt("data.txt", dtype=int, delimiter=",")
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [68]:
arr = np.loadtxt("data.txt", dtype='S')
arr

array([[b'1,', b'2,', b'3'],
       [b'4,', b'5,', b'6']], dtype='|S2')